version: '3.4'

networks:
  ot-network:
    name: ot-network
    
services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    networks:
      - ot-network

  redis:
    image: redis:6.2.1
    ports:
    - 6379:6379
    networks:
      - ot-network

  api1:
    build:
      context: .
      dockerfile: OpenTelemetry.WebApi1/Dockerfile
    ports:
      - "5000:80"
    networks:
      - ot-network
    depends_on: 
      - jaeger
    environment:
      Jaeger__AgentHost: jaeger
      Jaeger__AgentPort: 6831
      Api2Endpoint: http://api2/WeatherForecast

  api2:
    build:
      context: .
      dockerfile: OpenTelemetry.WebApi2/Dockerfile
    ports:
      - "5001:80"
    networks:
      - ot-network
    depends_on: 
      - jaeger
      - redis
    environment:
      Jaeger__AgentHost: jaeger
      Jaeger__AgentPort: 6831
      Redis__Host: redis
      Redis__Port: 6379