version: '3.4'

networks:
  tracing:
    name: tracing-network
    
services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686
    networks:
      - tracing

  api1:
    build:
      context: .
      dockerfile: OpenTelemetry.WebApi1/Dockerfile
    ports:
      - "5000:80"
    networks:
      - tracing
    depends_on: 
      - jaeger
    environment:
      Jaeger__AgentHost: jaeger
      Jaeger__AgentPort: 6831
      Api2Endpoint: http://api2/WeatherForecast

  api2:
    build:
      context: .
      dockerfile: OpenTelemetry.WebApi2/Dockerfile
    ports:
      - "5001:80"
    networks:
      - tracing
    depends_on: 
      - jaeger
    environment:
      Jaeger__AgentHost: jaeger
      Jaeger__AgentPort: 6831
